### ISSUE TITLE
DaVinci 1.0A stops mid print

### ISSUE THREAD

**Issue by mkvetny** [luc-github/Repetier-Firmware-0.92#135]
I recently flashed my DaVinci 1.0a with repetier 0.92 firmware, and am running repetier host 1.6.0. There were no problems with the installation, or the manual calibration. The problem occurs when printing.  The print starts normally and will run for about 20 min or so, after which the printer stops. One command is listed as held in buffer, the menu on the front panel can be navigated. The printer is completely unresponsive to repetier host. I looked through the g-code and didnt see anything out of the ordinary about the last command sent. If you have any questions please feel free to ask. Any help is greatly appreciated.

**Comment by luc-github** [comment]
Looks like same issue as https://github.com/luc-github/Repetier-Firmware-0.92/issues/38
the problem is linked to usb Davinci port sometimes got noise and loose connection
I fix should be available in test branch - https://github.com/luc-github/Repetier-Firmware-0.92/tree/0.92.6-sync but as I do not have a printer right now to test the code until march - I cannot validate the code
You can give a try 
Or you can print from SD which is always more reliable than USB, ( I never print from USB)

**Comment by luc-github** [comment]
If no update I will close as duplicate as https://github.com/luc-github/Repetier-Firmware-0.92/issues/38

**Comment by mkvetny** [comment]
I haven't had an opportunity to try it just yet. Ill let you know.

On Tue, Jan 26, 2016 at 2:58 AM, Luc <notifications@github.com> wrote:

> If no update I will close as duplicate as #38
> <https://github.com/luc-github/Repetier-Firmware-0.92/issues/38>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luc-github/Repetier-Firmware-0.92/issues/135#issuecomment-174881964>
> .
>



-- 
Maksim M. Kvetny
PhD Candidate
404-625-2284
