### ISSUE TITLE
Repurpose Fan Noise Issue & Manual Bed Leveling Feature Request

### ISSUE THREAD

**Issue by ngen33r** [luc-github/Repetier-Firmware-0.92#232]
I see that this issue has been addressed in the past but I just updated to 0.92.10 and when I have the fan plugged in the readings go crazy with the E3D thermistor. When the fan is not plugged in it works as intended. 

With a change in Z for the hot end the extruder crashes into the bed during manual leveling. Can we add an option to read the Z min pos from eeprom and move to Z min pos first before leveling the bed.

**Comment by luc-github** [comment]
Looks like 2 different issues/requests, pls avoid this, better to have one ticket by issue because it is not easy to follow answer for both issues at once, so I give first feedback be please reopen splitting issues to 2 tickets

about fan issue what changes did you do  in configuration.h to have this repurpose fan ? what is your printer model ? what is the firmware version ? (not the 0.92B but the one in settings/system version)

about manual bed leveling:
even using z min feature you describe, it won't prevent a possible crash on bed if screw are not at maximum and/or not close distance to any Zmin  (which should be 0)
The manual bed leveling pre requirement for the first usage is screws are at maximum then you release them until you reach Zmin (again should be 0) 
I think adding such option will be confusing and won't solve any crash as you do bed leveling because actuall zmin is not correct so using as reference is wrong approach
