### ISSUE TITLE
At what temp does PTFE begin to melt?  (Temp Tables?)

### ISSUE THREAD

**Issue by jsnbrgg** [luc-github/Repetier-Firmware-0.92#70]
While trying different settings to eliminate this massive de-lamination problem I'm having, I've noticed that any time I push my MK8 hotend past 230c the small PTFE tube inside the hotend begins to soften and causes major jams.  I have to replace to PTFE tube to fix it.  So according to Google PTFE doens't melt until over 300c.  So does that mean my temp tables are way off?  I've tried both #5 and #8

**Comment by luc-github** [comment]
sorry do you use stock thermistor ? if you use another one and trying other table I guess you are not
if not, using  tables are not accurate because  they are for Ramps not for Davinci board so temperature s can be out of range very easily

**Comment by jsnbrgg** [comment]
I'm using the Semitec 104GT-2 Thermistor.

Here is a link to the exact ones that I have:
http://www.amazon.com/gp/product/B00GWA2TZ6/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

**Comment by luc-github** [comment]
as said table in repetier FW are not for davinci board and are not valid because for RAMPS - so it is sure the temperatures you see on LCD are not corrects - only the custom table used with stock FW are working with DV board - if you use another sensor you have to redo the table - the custom table has been done drilling a hole in extruder close to sensor and using a thermocouple to build a table : ADC value + measured values

**Comment by jsnbrgg** [comment]
Ok..  cool.. that gives me an idea.  Thanks!

**Comment by luc-github** [comment]
If nothing more on it I close it

**Comment by jsnbrgg** [comment]
Yes, that's ok.. Thanks

**Comment by luc-github** [comment]
adding link for reference
http://voltivo.com/forum/davinci-firmware/438-repetier-91-e3d-v6-extruder#3631
