### ISSUE TITLE
Thermister for E3D V6

### ISSUE THREAD

**Issue by lyweilian** [luc-github/Repetier-Firmware-0.92#85]
On the E3D website it says to change the firmware EXT0_TEMPSENSOR_TYPE setting to 8 for "ATC Semitec 104-GT2". I did this and then the temperature shows as a -4 for the extruder. This does not seem right. I reverted it back to 5 and it seems to be more correct. Is this a bug or am I missing something. 

Here is the link on E3D: http://wiki.e3d-online.com/wiki/E3D-v6_Assembly#Repetier

**Comment by luc-github** [comment]
It is not a bug, because DAVINCI is not like a reprap board they do modification so cannot apply table like this, you need to create a custom table or use same sensor for which we create the custome table which I do not know the model so far.

you have a clean explanation here :
http://voltivo.com/forum/davinci-firmware/438-repetier-91-e3d-v6-extruder#3631
